version: '3'

services:
  nats-server:
    container_name: nats-server
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/tienda-microservicios-pabloh/image-registry/client-gateway:latest
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=${CLIENT_GATEWAY_PORT}

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/tienda-microservicios-pabloh/image-registry/products-ms:latest
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3001
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: southamerica-east1-docker.pkg.dev/tienda-microservicios-pabloh/image-registry/orders-ms:latest
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3002
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/tienda-microservicios-pabloh/image-registry/payments-ms:latest
    ports:
      - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=${PAYMENTS_MS_PORT}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/tienda-microservicios-pabloh/image-registry/auth-ms:latest
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3004
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
