version: '3'

services:
  nats-server:
    container_name: nats-server
    image: nats:latest
    ports:
      - "8222:8222"

  orders-db:
    container_name: orders-database
    image: postgres:16
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb

#========================
#CLIENT-GATEWAY
#=======================
  client-gateway:
    container_name: client-gateway
    build: ./client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000"
    develop:
      watch:
        - action: sync
          path: ./client-gateway/src
          target: /usr/src/app/src
          ignore:
            - node_modules
            - dist
            - .git
    command: pnpm run start:dev
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3000

#========================
#PRODUCTS-MS
#=======================
  products-ms:
    container_name: products-ms
    build: ./products-ms
    develop:
      watch:
        - action: sync
          path: ./products-ms/src
          target: /usr/src/app/src
          ignore:
            - node_modules
            - dist
            - .git
    command: pnpm run start:dev
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3001
      - DATABASE_URL=file:./dev.db

#========================
#ORDERS-MS
#=======================
  orders-ms:
    container_name: orders-ms
    depends_on:
      - orders-db
    build: ./orders-ms
    develop:
      watch:
        - action: sync
          path: ./orders-ms/src
          target: /usr/src/app/src
          ignore:
            - node_modules
            - dist
            - .git
    command: pnpm run start:dev
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public

#========================
#PAYMENT-MS
#=======================
  payments-ms:
    container_name: payments-ms
    build: ./payments-ms
    develop:
      watch:
        - action: sync
          path: ./payments-ms/src
          target: /usr/src/app/src
          ignore:
            - node_modules
            - dist
            - .git
    command: pnpm run start:dev
    ports:
      - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=${PAYMENTS_MS_PORT}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}



